import type { ScannerPlugin } from "./contracts.js";
import { patternRule } from "./rule-utils.js";
import { refs } from "./standards.js";

const redactSecret = (evidence: string): string => evidence.replace(/([:=]\s*)["'`]?[A-Za-z0-9_\-/.+=]{8,}["'`]?$/i, "$1[REDACTED]");

export const builtinPlugin: ScannerPlugin = {
  name: "@lego-scan/builtin",
  version: "0.3.0",
  rules: [
    patternRule({
      id: "security/no-hardcoded-secret",
      description: "检测疑似硬编码密钥",
      severity: "high",
      confidence: "medium",
      category: "security",
      tags: ["credentials", "secrets"],
      references: [refs.cwe("CWE-798"), refs.ssdf("PW.9"), refs.asvs("V14.3")],
      codeOnly: true,
      pattern: /(?:api[_-]?key|secret|token|password)\s*[:=]\s*["'`]?[A-Za-z0-9_\-/.+=]{8,}["'`]?/i,
      message: "发现疑似硬编码凭据。",
      suggestion: "通过环境变量或密钥管理服务注入凭据，并立即轮换已暴露的密钥。",
      redactEvidence: redactSecret,
    }),
    patternRule({
      id: "security/no-eval",
      description: "禁止执行动态字符串代码",
      severity: "high",
      confidence: "high",
      category: "security",
      tags: ["injection", "dynamic-code"],
      references: [refs.cwe("CWE-95"), refs.asvs("V5"), refs.wstg("WSTG-INPV")],
      pattern: /\beval\s*\(/,
      message: "使用 eval 可能导致代码注入。",
      suggestion: "使用显式解析或安全的数据映射替代 eval。",
    }),
    patternRule({
      id: "security/no-function-constructor",
      description: "禁止 Function 构造器",
      severity: "high",
      confidence: "high",
      category: "security",
      tags: ["injection", "dynamic-code"],
      references: [refs.cwe("CWE-95"), refs.asvs("V5")],
      pattern: /\bnew\s+Function\s*\(/,
      message: "Function 构造器会执行动态代码。",
      suggestion: "移除动态代码执行，改用预定义函数。",
    }),
    patternRule({
      id: "security/no-command-injection",
      description: "检测可能的命令注入",
      severity: "critical",
      confidence: "medium",
      category: "security",
      tags: ["injection", "command"],
      references: [refs.cwe("CWE-78"), refs.ssdf("PW.7"), refs.asvs("V5"), refs.wstg("WSTG-INPV")],
      pattern: /\b(?:exec|execSync)\s*\(\s*(?:`[^`]*\$\{|[^)]*\+)/,
      message: "动态内容被拼接到系统命令中。",
      suggestion: "使用 execFile/spawn 的参数数组，并对白名单参数进行校验。",
    }),
    patternRule({
      id: "security/no-disabled-tls-verification",
      description: "禁止关闭 TLS 证书校验",
      severity: "critical",
      confidence: "high",
      category: "configuration",
      tags: ["tls", "transport-security"],
      references: [refs.cwe("CWE-295"), refs.asvs("V9"), refs.wstg("WSTG-CRYP")],
      pattern: /rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0/,
      message: "TLS 证书校验被禁用。",
      suggestion: "恢复证书校验并配置可信 CA。",
    }),
    patternRule({
      id: "testing/no-skipped-test",
      description: "检测被跳过的测试",
      severity: "medium",
      category: "testing",
      tags: ["verification", "test-quality"],
      references: [refs.ssdf("PW.8"), refs.samm("Verification/Security Testing")],
      testsOnly: true,
      pattern: /^\s*(?:it|test|describe)\.skip\s*\(/,
      message: "存在被跳过的测试。",
      suggestion: "修复并启用测试，或记录带期限的例外原因。",
    }),
    patternRule({
      id: "testing/no-focused-test",
      description: "检测仅运行的聚焦测试",
      severity: "high",
      category: "testing",
      tags: ["verification", "test-quality"],
      references: [refs.ssdf("PW.8"), refs.samm("Verification/Security Testing")],
      testsOnly: true,
      pattern: /^\s*(?:it|test|describe)\.only\s*\(/,
      message: "聚焦测试会导致其他测试不执行。",
      suggestion: "提交前移除 .only。",
    }),
    patternRule({
      id: "testing/no-empty-test",
      description: "检测空测试体",
      severity: "medium",
      category: "testing",
      tags: ["verification", "test-quality"],
      references: [refs.ssdf("PW.8"), refs.samm("Verification/Requirements-driven Testing")],
      testsOnly: true,
      pattern: /^\s*(?:it|test)\s*\([^,]+,\s*(?:async\s*)?\(.*?\)\s*=>\s*\{\s*\}\s*\)/,
      message: "测试体为空，无法验证行为。",
      suggestion: "添加有效执行步骤和断言。",
    }),
    patternRule({
      id: "testing/no-always-true-assertion",
      description: "检测恒真断言",
      severity: "medium",
      category: "testing",
      tags: ["verification", "assertion"],
      references: [refs.ssdf("PW.8"), refs.samm("Verification/Requirements-driven Testing")],
      testsOnly: true,
      pattern: /^\s*expect\s*\(\s*true\s*\)\s*\.toBe\s*\(\s*true\s*\)/,
      message: "恒真断言无法验证业务行为。",
      suggestion: "对实际返回值或状态变化进行断言。",
    }),
    patternRule({
      id: "security/no-private-key",
      description: "检测提交到源码中的私钥",
      severity: "critical",
      confidence: "high",
      category: "security",
      tags: ["credentials", "private-key"],
      references: [refs.cwe("CWE-321"), refs.ssdf("PW.9"), refs.asvs("V14.3")],
      pattern: /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,
      message: "发现私钥内容。",
      suggestion: "立即撤销并轮换对应密钥，从源码和 Git 历史中彻底清除私钥。",
      redactEvidence: () => "[REDACTED PRIVATE KEY]",
    }),
    patternRule({
      id: "security/no-cloud-access-key",
      description: "检测云服务访问密钥",
      severity: "critical",
      confidence: "high",
      category: "security",
      tags: ["credentials", "cloud"],
      references: [refs.cwe("CWE-798"), refs.ssdf("PW.9"), refs.asvs("V14.3")],
      pattern: /\bAKIA[0-9A-Z]{16}\b/,
      message: "发现疑似云服务访问密钥。",
      suggestion: "立即禁用并轮换密钥，改用工作负载身份或密钥管理服务。",
      redactEvidence: () => "[REDACTED ACCESS KEY]",
    }),
    patternRule({
      id: "configuration/no-debug-mode",
      description: "检测生产配置中的调试模式",
      severity: "high",
      confidence: "medium",
      category: "configuration",
      tags: ["debug", "information-disclosure"],
      references: [refs.cwe("CWE-489"), refs.asvs("V14")],
      pattern: /(?:APP_DEBUG|DEBUG|debug)\s*[:=]\s*(?:true|1|on)\b/i,
      message: "配置中启用了调试模式。",
      suggestion: "生产环境关闭调试模式，并限制详细错误信息仅在受控环境可见。",
    }),
    patternRule({
      id: "configuration/no-wildcard-cors",
      description: "检测允许任意来源的 CORS 配置",
      severity: "high",
      confidence: "medium",
      category: "configuration",
      tags: ["cors", "access-control"],
      references: [refs.cwe("CWE-942"), refs.asvs("V4")],
      pattern: /(?:Access-Control-Allow-Origin|allowedOrigins?|corsOrigins?)\s*[:=]\s*["']?\*["']?/i,
      message: "CORS 配置允许任意来源。",
      suggestion: "使用明确的可信来源白名单，并避免与凭据模式同时启用。",
    }),
    patternRule({
      id: "configuration/no-insecure-cookie",
      description: "检测不安全的 Cookie 配置",
      severity: "medium",
      confidence: "medium",
      category: "configuration",
      tags: ["cookie", "session"],
      references: [refs.cwe("CWE-614"), refs.asvs("V3")],
      pattern: /(?:cookie_secure|secure)\s*[:=]\s*false|SameSite\s*[:=]\s*["']?none["']?(?![\s\S]*secure)/i,
      message: "Cookie 安全属性可能被禁用。",
      suggestion: "会话 Cookie 应启用 Secure、HttpOnly，并设置适当的 SameSite 策略。",
    }),
    patternRule({
      id: "security/no-sql-injection",
      description: "检测将外部输入拼接到 SQL 语句",
      severity: "high",
      confidence: "medium",
      category: "security",
      tags: ["injection", "sql"],
      references: [refs.cwe("CWE-89"), refs.asvs("V5.3"), refs.wstg("WSTG-INPV")],
      codeOnly: true,
      pattern: /\b(?:SELECT|INSERT|UPDATE|DELETE|DROP)\b[^\n]{0,120}(?:\$\{[^}]+\}|(?:\+\s*["'`]?[$A-Za-z_][\w$]*)|["'`][^"'`\n]{0,80}\s*\+\s*[$A-Za-z_])/i,
      message: "SQL 语句可能拼接了外部输入，存在注入风险。",
      suggestion: "使用参数化查询或预编译语句，切勿将用户输入直接拼入 SQL 字符串。",
    }),
    patternRule({
      id: "security/no-xss",
      description: "检测未编码直接写入 HTML 或响应的危险赋值",
      severity: "high",
      confidence: "medium",
      category: "security",
      tags: ["xss", "injection"],
      references: [refs.cwe("CWE-79"), refs.asvs("V5.3"), refs.wstg("WSTG-CLNT")],
      codeOnly: true,
      pattern: /(?:\.(?:innerHTML|outerHTML)\s*=|dangerouslySetInnerHTML|document\.write\s*\(|res\.(?:send|write|end)\s*\(\s*[^)\n]*\$\{[^}]+\})/i,
      message: "内容可能未经编码直接写入页面或响应，存在 XSS 风险。",
      suggestion: "使用安全的渲染 API（如 textContent）或对输出进行上下文转义（如转义 HTML/属性）。",
    }),
    patternRule({
      id: "security/no-ssrf",
      description: "检测以请求/用户输入作为出站请求目标",
      severity: "high",
      confidence: "medium",
      category: "security",
      tags: ["ssrf", "injection"],
      references: [refs.cwe("CWE-918"), refs.asvs("V5.2"), refs.wstg("WSTG-INPV")],
      codeOnly: true,
      pattern: /\b(?:fetch|axios\.(?:get|post|put|delete)|https?\.get|http\.get|request|got)\s*\(\s*(?:req\.|request\.|user|params|query|body|input|url)/i,
      message: "出站请求目标可能由外部输入控制，存在 SSRF 风险。",
      suggestion: "对请求地址做白名单校验或限制内网/元数据地址访问，并禁用非必要协议。",
    }),
    patternRule({
      id: "security/no-path-traversal",
      description: "检测将用户输入拼接到文件路径",
      severity: "high",
      confidence: "medium",
      category: "security",
      tags: ["path-traversal", "file"],
      references: [refs.cwe("CWE-22"), refs.asvs("V12.3"), refs.wstg("WSTG-AUTH")],
      codeOnly: true,
      pattern: /\b(?:fs\.(?:readFile|readFileSync|writeFile|writeFileSync|existsSync|unlinkSync)|path\.join|createReadStream|createWriteStream)\s*\([^)]{0,80}(?:req\.|request\.|user|params|query|body|input|path)|(?:\.\.\/|\.\.\\)[^"'`\n]{0,40}(?:req\.|user|params|query|body)/i,
      message: "文件路径可能受外部输入控制，存在路径穿越风险。",
      suggestion: "对文件名做规范化与基目录约束，拒绝包含 '../' 或绝对路径的用户输入。",
    }),
    patternRule({
      id: "security/no-weak-hash",
      description: "检测使用了已被攻破的哈希算法（MD5/SHA1）",
      severity: "medium",
      confidence: "medium",
      category: "security",
      tags: ["crypto", "hash"],
      references: [refs.cwe("CWE-328"), refs.asvs("V6.1")],
      codeOnly: true,
      pattern: /\b(?:md5|sha1)\s*\(|createHash\s*\(\s*["'](?:md5|sha1)["']/i,
      message: "使用了弱哈希算法（MD5/SHA1）。",
      suggestion: "密码散列使用 bcrypt/argon2/scrypt；完整性校验使用 SHA-256 及以上。",
    }),
    patternRule({
      id: "security/no-insecure-deserialization",
      description: "检测危险的反序列化调用",
      severity: "high",
      confidence: "medium",
      category: "security",
      tags: ["deserialization", "injection"],
      references: [refs.cwe("CWE-502"), refs.asvs("V5.5")],
      codeOnly: true,
      pattern: /\b(?:unserialize|pickle\.loads?|yaml\.load|deserialize|node-serialize)\s*\(/i,
      message: "存在不安全的反序列化调用。",
      suggestion: "避免反序列化不可信数据；若必须，使用带类型校验的安全序列化（如 JSON）并限制来源。",
    }),
    patternRule({
      id: "security/no-open-redirect",
      description: "检测以用户输入为目标的开放重定向",
      severity: "medium",
      confidence: "medium",
      category: "security",
      tags: ["redirect", "open-redirect"],
      references: [refs.cwe("CWE-601"), refs.asvs("V4.4")],
      codeOnly: true,
      pattern: /\b(?:res|response)\.redirect\s*\(\s*(?:req\.|request\.|user|params|query|body|input|url)/i,
      message: "重定向目标可能由外部输入控制，存在开放重定向风险。",
      suggestion: "对重定向地址做白名单或相对路径校验，禁止任意外部跳转。",
    }),
    patternRule({
      id: "security/no-insecure-randomness",
      description: "检测在安全敏感场景使用不安全随机数",
      severity: "low",
      confidence: "low",
      category: "security",
      tags: ["random", "crypto"],
      references: [refs.cwe("CWE-330"), refs.asvs("V6.3")],
      codeOnly: true,
      pattern: /\b(?:token|secret|password|passwd|session|cookie|apikey|api_key|csrf|nonce)\b[^;]{0,60}Math\.random|Math\.random[^;]{0,60}(?:token|secret|password|session|cookie|key|csrf|nonce)/i,
      message: "安全敏感值可能使用了不安全的随机数（Math.random）。",
      suggestion: "安全用途（令牌/密钥/OTP）应使用 crypto.randomBytes 等密码学安全随机数。",
    }),
  ],
};
